default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: postgres
  password: admin

development:
  <<: *default
  database: transportation_v1_development

test:
  <<: *default
  database: transportation_v1_test

production:
  <<: *default
  database: transportation_v1_production
  username: transportation_v1
  password: <%= ENV['TRANSPORTATION_V1_DATABASE_PASSWORD'] %>
